using Microsoft.AspNetCore.Mvc;
using NeonBank.Data;
using NeonBank.Models;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace NeonBank.Controllers
{
    public class AccountController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AccountController(ApplicationDbContext context)
        {
            _context = context;
        }

        // --- REGISTRATION ---
        [HttpGet]
        public IActionResult Register()
        {
            if (User.Identity?.IsAuthenticated == true)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(User model)
        {
            if (!ModelState.IsValid)
                return View(model);

            // Check if email already exists
            bool emailExists = await _context.Users.AnyAsync(u => u.Email == model.Email);
            if (emailExists)
            {
                ModelState.AddModelError("Email", "This email is already registered.");
                return View(model);
            }

            // Assign default role
            model.Role = "Customer";

            // ✅ FIX: Save user FIRST so UserId is generated by the database
            _context.Users.Add(model);
            await _context.SaveChangesAsync(); // UserId is now populated

            // ✅ FIX: Now UserId is valid — create the linked account
            var account = new Account
            {
                UserId = model.UserId,
                AccountNumber = "NB-" + new Random().Next(1000000, 9999999).ToString(),
                Balance = 500.00m // Welcome bonus
            };
            _context.Accounts.Add(account);
            await _context.SaveChangesAsync();

            TempData["Success"] = "Account created successfully! You received a $500 welcome bonus. Please log in.";
            return RedirectToAction("Login");
        }

        // --- LOGIN ---
        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity?.IsAuthenticated == true)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string email, string password)
        {
            if (string.IsNullOrWhiteSpace(email) || string.IsNullOrWhiteSpace(password))
            {
                ViewBag.Error = "Please enter both email and password.";
                return View();
            }

            // ✅ NOTE: In production, use hashed passwords (BCrypt). 
            // For now matching plain text as per original project design.
            var user = await _context.Users
                .FirstOrDefaultAsync(u => u.Email == email && u.Password == password);

            if (user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.FullName),
                    new Claim(ClaimTypes.NameIdentifier, user.UserId.ToString()),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim(ClaimTypes.Role, user.Role)
                };

                var identity = new ClaimsIdentity(claims, "CookieAuth");
                var principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync("CookieAuth", principal);
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Error = "Invalid email or password. Please try again.";
            return View();
        }

        // --- LOGOUT ---
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("CookieAuth");
            return RedirectToAction("Login");
        }
    }
}
